name: Java Gradle CI Build
trigger:
  branches:
    include:
      - ref/heads/development
      - ref/heads/feature/*
      - ref/heads/release/*
      - ref/heads/bugfix/*
      - ref/heads/hotfix/*
    exclude:
      - ref/heads/master
  paths:
    exclude:
      - "azure/**/*.yml"

pr: none

pool:
  vmImage: ubuntu-latest

variables:
- group: HELM_VARIABLES
- group: DOCKER_VARIABLES

resources:
 repositories:
   - repository: fsm-akka-azure-pipelines
     type: github
     name: mehmetsalgar/fsm-akka-azure-pipelines
     endpoint: mehmetsalgar

stages:
- stage: Build
  displayName: Build
  jobs:
  - template: build.yml@fsm-akka-azure-pipelines
    parameters:
      sourceRepo: 'fraud-prevention-application'
