name: Cleanup Environment with Reuse
trigger: none

parameters:
  - name: branchName
    type: string

pool:
  vmImage: ubuntu-latest

variables:
  - group: HELM_VARIABLES
  - group: DOCKER_VARIABLES

resources:
  repositories:
    - repository: fsm-akka-azure-pipelines
      type: github
      name: mehmetsalgar/fsm-akka-azure-pipelines
      endpoint: mehmetsalgar

stages:
  - stage: Deploy
    jobs:
      - job: CleanServiceEnvironment
        steps:
          - template: cleanup-environment.yml@fsm-akka-azure-pipelines
            parameters:
              branchName: "feature/${{ parameters.branchName }}-fraud-prevention"
