name: Contionuous Deployment for Development

resources:
  pipelines:
   - pipeline: Build
     source: Build-with-Reusable
     trigger: true
  repositories:
   - repository: fsm-akka-azure-pipelines
     type: github
     name: mehmetsalgar/fsm-akka-azure-pipelines
     endpoint: mehmetsalgar

steps:
  - pwsh: |
      echo 'Halli Hallo'
  
  - template: dispatch.yml@fsm-akka-azure-pipelines
    parameters:
      definitionId: "9"
      branchName: "development"
      inputs: '"sourceRepo": "fraud-prevention"'
