name: Contionuous Deployment for Development

resources:
  pipelines:
   - pipeline: Build
     source: azure-pipelines.yaml
     trigger: true

pool:
  vmImage: 'ubuntu-latest'

steps:
  - pwsh: |
      echo "Halli Hallo"