name: Continuous Deployment Caller - Development
run-name: Continuous Deployment for Development triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_run:
    workflows: [Java / Gradle CI Caller]
    branches: [development]
    types: [completed]

jobs:
  call-continuous-deployment-workflow:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/continuous-deployment-development.yaml@master
    with:
      repo-name: "fraud-prevention"
      branch-name: "${{ github.event.workflow_run.head_branch }}"
    secrets: inherit