name: Continuous Deployment Caller - Release
run-name: Continuous Deployment for Release triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_run:
    workflows: [Java / Gradle CI Caller]
    branches: [release/**]
    types: [completed]
jobs:
  call-continuous-deployment-workflow:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/continuous-deployment-with-environment.yaml@master
    with:
      repo-name: "fraud-prevention"
      branch-name: "${{ github.event.workflow_run.head_branch }}"
      umbrella-chart-base-branch-name: "master"
      infrastructure-base-branch-name: "master"
      value-file: "values-release"
    secrets: inherit