name: Release GA
run-name: Release GA triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
  release-pre:
    runs-on: ubuntu-latest
    steps:
      - name: Releasing
        run: |
          echo 'Releasing'
  release:
    needs: [release-pre]
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/build.yaml@master